# Generated by Django 2.2.4 on 2019-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('contact_last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('contact_email', models.CharField(max_length=50, verbose_name='Email')),
                ('contact_massage', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
