# Generated by Django 2.2.4 on 2019-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(max_length=50, verbose_name='E-mail адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_massage',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
