# Generated by Django 2.2.4 on 2019-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery_famyly',
            options={'verbose_name': 'Семейная фотография', 'verbose_name_plural': 'Семейные фотографии'},
        ),
        migrations.AlterModelOptions(
            name='gallery_portrait',
            options={'verbose_name': 'Портрет', 'verbose_name_plural': 'Портреты'},
        ),
        migrations.AlterModelOptions(
            name='gallery_weding',
            options={'verbose_name': 'Свадебная фотография', 'verbose_name_plural': 'Свадебные фотографии'},
        ),
        migrations.AlterField(
            model_name='gallery_famyly',
            name='fam_img1',
            field=models.ImageField(upload_to='media/fam'),
        ),
        migrations.AlterField(
            model_name='gallery_famyly',
            name='fam_img2',
            field=models.ImageField(upload_to='media/fam'),
        ),
        migrations.AlterField(
            model_name='gallery_famyly',
            name='fam_img3',
            field=models.ImageField(upload_to='media/fam'),
        ),
        migrations.AlterField(
            model_name='gallery_famyly',
            name='fam_img4',
            field=models.ImageField(upload_to='media/fam'),
        ),
        migrations.AlterField(
            model_name='gallery_famyly',
            name='fam_img5',
            field=models.ImageField(upload_to='media/fam'),
        ),
        migrations.AlterField(
            model_name='gallery_famyly',
            name='fam_img6',
            field=models.ImageField(upload_to='media/fam'),
        ),
        migrations.AlterField(
            model_name='gallery_portrait',
            name='port_img1',
            field=models.ImageField(upload_to='media/por'),
        ),
        migrations.AlterField(
            model_name='gallery_portrait',
            name='port_img2',
            field=models.ImageField(upload_to='media/por'),
        ),
        migrations.AlterField(
            model_name='gallery_portrait',
            name='port_img3',
            field=models.ImageField(upload_to='media/por'),
        ),
        migrations.AlterField(
            model_name='gallery_portrait',
            name='port_img4',
            field=models.ImageField(upload_to='media/por'),
        ),
        migrations.AlterField(
            model_name='gallery_portrait',
            name='port_img5',
            field=models.ImageField(upload_to='media/por'),
        ),
        migrations.AlterField(
            model_name='gallery_portrait',
            name='port_img6',
            field=models.ImageField(upload_to='media/por'),
        ),
        migrations.AlterField(
            model_name='gallery_weding',
            name='wed_img1',
            field=models.ImageField(upload_to='media/wed'),
        ),
        migrations.AlterField(
            model_name='gallery_weding',
            name='wed_img2',
            field=models.ImageField(upload_to='media/wed'),
        ),
        migrations.AlterField(
            model_name='gallery_weding',
            name='wed_img3',
            field=models.ImageField(upload_to='media/wed'),
        ),
        migrations.AlterField(
            model_name='gallery_weding',
            name='wed_img4',
            field=models.ImageField(upload_to='media/wed'),
        ),
        migrations.AlterField(
            model_name='gallery_weding',
            name='wed_img5',
            field=models.ImageField(upload_to='media/wed'),
        ),
        migrations.AlterField(
            model_name='gallery_weding',
            name='wed_img6',
            field=models.ImageField(upload_to='media/wed'),
        ),
    ]
