# Generated by Django 2.2.4 on 2019-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_foto', models.ImageField(upload_to='media/me')),
            ],
            options={
                'verbose_name': 'Я на фотографии',
                'verbose_name_plural': 'Я на фотографиях',
            },
        ),
    ]
